/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sqltrainer.exercises;

import java.awt.CardLayout;
import java.util.List;

/**
 *
 * @author karlinsv
 */
public class ExerciseNewExerciseScreen extends javax.swing.JFrame {

    NewExerciseListener listener = null;
    
    /**
     * Creates new form ExerciseNewExerciseScreen
     */
    public ExerciseNewExerciseScreen(List<TopicItem> topics, NewExerciseListener listener) {
        this.listener = listener;
        initComponents();
        for(TopicItem item : topics) {
            this.topicList.addItem(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answerTypeGroup = new javax.swing.ButtonGroup();
        multipleChoiceAnswerGroup = new javax.swing.ButtonGroup();
        topicLabel = new javax.swing.JLabel();
        topicList = new javax.swing.JComboBox();
        titleLabel = new javax.swing.JLabel();
        titleText = new javax.swing.JTextField();
        questionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionText = new javax.swing.JTextArea();
        answerPanel = new javax.swing.JPanel();
        longAnswerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        longAnswerText = new javax.swing.JTextArea();
        multipleChoiceAnswerPanel = new javax.swing.JPanel();
        multipleChoiceAnswer1Button = new javax.swing.JRadioButton();
        multipleChoiceAnswer2Button = new javax.swing.JRadioButton();
        multipleChoiceAnswer3Button = new javax.swing.JRadioButton();
        multipleChoiceAnswer1Text = new javax.swing.JTextField();
        multipleChoiceAnswer2Text = new javax.swing.JTextField();
        multipleChoiceAnswer3Text = new javax.swing.JTextField();
        answerTypeText = new javax.swing.JRadioButton();
        answerTypeMultipleChoice = new javax.swing.JRadioButton();
        answerTypeLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Neue Übung");
        setResizable(false);

        topicLabel.setText("Thema");

        titleLabel.setText("Name");

        questionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Frage"));

        questionText.setColumns(20);
        questionText.setRows(5);
        jScrollPane1.setViewportView(questionText);

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );

        answerPanel.setLayout(new java.awt.CardLayout());

        longAnswerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Antwort"));

        longAnswerText.setColumns(20);
        longAnswerText.setRows(5);
        jScrollPane2.setViewportView(longAnswerText);

        javax.swing.GroupLayout longAnswerPanelLayout = new javax.swing.GroupLayout(longAnswerPanel);
        longAnswerPanel.setLayout(longAnswerPanelLayout);
        longAnswerPanelLayout.setHorizontalGroup(
            longAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        longAnswerPanelLayout.setVerticalGroup(
            longAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        answerPanel.add(longAnswerPanel, "longAnswerCard");

        multipleChoiceAnswerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Antwort"));

        multipleChoiceAnswerGroup.add(multipleChoiceAnswer1Button);

        multipleChoiceAnswerGroup.add(multipleChoiceAnswer2Button);

        multipleChoiceAnswerGroup.add(multipleChoiceAnswer3Button);

        multipleChoiceAnswer1Text.setToolTipText("Antwort Möglichkeit 1");

        multipleChoiceAnswer2Text.setToolTipText("Antwort Möglichkeit 2");

        multipleChoiceAnswer3Text.setToolTipText("Antwort Möglichkeit 3");

        javax.swing.GroupLayout multipleChoiceAnswerPanelLayout = new javax.swing.GroupLayout(multipleChoiceAnswerPanel);
        multipleChoiceAnswerPanel.setLayout(multipleChoiceAnswerPanelLayout);
        multipleChoiceAnswerPanelLayout.setHorizontalGroup(
            multipleChoiceAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleChoiceAnswerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multipleChoiceAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multipleChoiceAnswerPanelLayout.createSequentialGroup()
                        .addComponent(multipleChoiceAnswer3Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multipleChoiceAnswer3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multipleChoiceAnswerPanelLayout.createSequentialGroup()
                        .addComponent(multipleChoiceAnswer2Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multipleChoiceAnswer2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(multipleChoiceAnswerPanelLayout.createSequentialGroup()
                        .addComponent(multipleChoiceAnswer1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multipleChoiceAnswer1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        multipleChoiceAnswerPanelLayout.setVerticalGroup(
            multipleChoiceAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleChoiceAnswerPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(multipleChoiceAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multipleChoiceAnswer1Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multipleChoiceAnswer1Button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(multipleChoiceAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(multipleChoiceAnswer2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multipleChoiceAnswer2Button))
                .addGap(18, 18, 18)
                .addGroup(multipleChoiceAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multipleChoiceAnswer3Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multipleChoiceAnswer3Button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        answerPanel.add(multipleChoiceAnswerPanel, "multpileChoiceAnswerCard");

        answerTypeGroup.add(answerTypeText);
        answerTypeText.setSelected(true);
        answerTypeText.setText("Text");
        answerTypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTypeTextActionPerformed(evt);
            }
        });

        answerTypeGroup.add(answerTypeMultipleChoice);
        answerTypeMultipleChoice.setText("Multiple Choice");
        answerTypeMultipleChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTypeMultipleChoiceActionPerformed(evt);
            }
        });

        answerTypeLabel.setText("Antwort Typ");

        submitButton.setText("Speichern");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(questionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(topicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answerTypeText)
                                .addGap(18, 18, 18)
                                .addComponent(answerTypeMultipleChoice)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(topicList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicLabel)
                    .addComponent(topicList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerTypeText)
                    .addComponent(answerTypeMultipleChoice)
                    .addComponent(answerTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(questionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerTypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTypeTextActionPerformed
        CardLayout cl = (CardLayout)(answerPanel.getLayout());
        cl.show(answerPanel, "longAnswerCard");
    }//GEN-LAST:event_answerTypeTextActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(listener != null) {
            listener.onCancel(this);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(answerTypeText.isSelected()) {
            submitExerciseDataText();
        } else if(answerTypeMultipleChoice.isSelected()) {
            submitExerciseDataMultipleChoice();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void answerTypeMultipleChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTypeMultipleChoiceActionPerformed
        CardLayout cl = (CardLayout)(answerPanel.getLayout());
        cl.show(answerPanel, "multpileChoiceAnswerCard");
    }//GEN-LAST:event_answerTypeMultipleChoiceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel answerPanel;
    private javax.swing.ButtonGroup answerTypeGroup;
    private javax.swing.JLabel answerTypeLabel;
    private javax.swing.JRadioButton answerTypeMultipleChoice;
    private javax.swing.JRadioButton answerTypeText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel longAnswerPanel;
    private javax.swing.JTextArea longAnswerText;
    private javax.swing.JRadioButton multipleChoiceAnswer1Button;
    private javax.swing.JTextField multipleChoiceAnswer1Text;
    private javax.swing.JRadioButton multipleChoiceAnswer2Button;
    private javax.swing.JTextField multipleChoiceAnswer2Text;
    private javax.swing.JRadioButton multipleChoiceAnswer3Button;
    private javax.swing.JTextField multipleChoiceAnswer3Text;
    private javax.swing.ButtonGroup multipleChoiceAnswerGroup;
    private javax.swing.JPanel multipleChoiceAnswerPanel;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JTextArea questionText;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleText;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JComboBox topicList;
    // End of variables declaration//GEN-END:variables

    private void submitExerciseDataText() {
        int topic = ((TopicItem)topicList.getModel().getSelectedItem()).getId();
        String title = titleText.getText();
        String question = questionText.getText();
        String answer = longAnswerText.getText();
        if(listener != null) {
            listener.onSubmitTextAnswer(this, topic, title, question, answer);
        }
    }

    private void submitExerciseDataMultipleChoice() {
        int topic = ((TopicItem)topicList.getModel().getSelectedItem()).getId();
        String title = titleText.getText();
        String question = questionText.getText();
        String[] answers = {this.multipleChoiceAnswer1Text.getText(), this.multipleChoiceAnswer2Text.getText(),this.multipleChoiceAnswer3Text.getText()};
        int answer = this.multipleChoiceAnswer1Button.isSelected() ? 1 : this.multipleChoiceAnswer2Button.isSelected() ? 2 : 3;
        if(listener != null) {
            listener.onSubmitMultipleChoiceAnswer(this, topic, title, question, answers, answer);
        }
    }
}
